no healthcheck

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,7 +22,7 @@ jobs:
         image: mysql:5.7
         ports:
           - 3306  
-        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
+        #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
 
     container: python:3.10
 
@@ -35,19 +35,19 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
-      - name: sudo install mariadb-dev package
-        run: apt-get install libmariadb-dev
+      # - name: Install mariadb-dev package
+      #   run: apt-get install libmariadb-dev
       - name: update pip
         run: python -m pip install --upgrade pip
       - name: install all dependencies
         run: pip install -r requirements.txt
-      # - name: Wait for db container
-        # env:
-        #   PORT: ${{ job.services.mariadb.ports[3306] }}
-        # run: |
-        #     while ! mysqladmin ping -h"0.0.0.0" -P"$PORT" -u ${MARIADB_USER} -p${MARIADB_PASSWORD}; do
-        #       sleep 1
-        #     done    
+      - name: Wait for db container
+        env:
+          PORT: ${{ job.services.mariadb.ports[3306] }}
+        run: |
+            while ! mysqladmin --help
+              sleep 1
+            done    
       - name: test with pytest
         run: |
           PYTHONPATH=${PYTHONPATH}:./src python -m pytest
